plugins {
    id 'java'
    id 'application'
    id 'io.freefair.lombok' version '8.6'
    id 'com.google.protobuf' version '0.10.0'
}

group = 'org.photonflight'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

application {
    mainModule.set('org.photonflight.core')
    mainClass.set('org.photonflight.core.HelloApplication')
}

def junitVersion = '5.12.1'
dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"

    // Google Auto
    compileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.1.1'

    // Google Guice
    implementation "com.google.inject:guice:7.0.0"

    // GRPC Protobuf
    implementation 'io.grpc:grpc-protobuf:1.84.1'
    implementation 'io.grpc:grpc-stub:1.84.1'
    implementation 'io.grpc:grpc-netty-shaded:1.84.1'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:4.36.2'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.84.1'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir 'proto'
        }
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
